config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root 'statics#index'
  
  resources :places do
    resources :comments, only: [:create, :update]
    resources :photos, only: :create
    collection do
      get :search, to: "places#search"
    end
  end
  
  resources :users, only: [:show, :update]
  resource :dashboard, only: [:show]
  
  namespace :admin do
    resources :places, only: [:destroy]
  end
  
  resources :buckets, only: [:update, :destroy]  
  resources :completed_buckets, only: [:index, :destroy]
  
  get "/places/:place_id/photos", to: "galleries#index", as: "galleries"
  
  resources :photos, only: [:show, :destroy]
  
  
  get 'bucketlist', to: 'buckets#index'
  post 'bucketlist', to: 'buckets#create'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email
  
  validates :message, presence: true
  
  def send_comment_email
    if place.user
      if place.user.notify_on_comment == true
        NotificationMailer.comment_added(self).deliver_now
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.build(comment_params)
    if @comment.save
      flash[:notice] = "Your comment has been posted."
      respond_to do |format| 
        format.html { redirect_to place_path(@place) }
        format.js
      end
    else
      @comments = @place.comments.reload
      if @comment.errors.full_messages.present?
        flash[:alert] = @comment.errors.full_messages[0]
      else
        flash[:alert] = "Your comment did not post"
      end
      #redirect_to :back
      respond_to do |format| 
        format.html { redirect_to :back }
        format.js
      end
    end
  end
  
  def update
    @comment = Comment.find(params[:id])
    @place = @comment.place
    return render text: 'Not Allowed', status: :forbidden unless @comment.user == current_user || current_user.admin?
    @comment.update_attributes(comment_params)
    if @comment.valid?
      flash[:notice] = "Your comment has been updated."
      redirect_to place_path(@place)
#       respond_to do |format| 
#         format.html { redirect_to place_path(@place) }
#         format.js
#      end
    else
      @comments = @place.comments.reload
      if @comment.errors.full_messages.present?
        flash[:alert] = @comment.errors.full_messages[0]
      else
        flash[:alert] = "Your comment did not update"
      end
      redirect_to :back
#       respond_to do |format| 
#         format.html { redirect_to :back }
#         format.js
#      end
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:message, :rating).merge(user: current_user)
  end
end


 
  

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<blockquote>
    <b><%= comment.rating %></b> -
      <%= comment.message %>
    <small><%= link_to comment.user.username, user_path(comment.user) %></small>
  </blockquote> 

  <% if current_user %>
    <% if current_user == comment.user || current_user.admin? %>
      <!-- Modal -->
      <div class="modal fade" id="commentUpdate<%= comment.id %>Modal" tabindex="-1" role="dialog" aria-labelledby="commentUpdate<%= comment.id %>Modal" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="commentUpdate<%= comment.id %>Modal">Add a comment</h4>
            </div>
            <div class="modal-body">
                <%= simple_form_for comment, url: place_comment_path(@place, comment) do |f| %>
                <%= f.collection_radio_buttons :rating, [[1, image_tag('star-empty.png')] ,[2, image_tag('star-empty.png')], [3, image_tag('star-empty.png')], [4, image_tag('star-empty.png')], [5, image_tag('star-empty.png')]], :first, :last %>
                <%= f.input :message, label: "Your comment" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Edit Comment", class: 'btn btn-primary' %>
            </div>
            <% end %>  
        </div>
      </div>
    </div>
    <div class="clear"></div>      
    <button class="btn btn-primary pull-left" data-toggle="modal" data-target="#commentUpdate<%= comment.id %>Modal">
      Edit Comment
    </button> 
    <br />
    <% end %>
  <% end %>

app/views/comments/_form.html.erb
<%= simple_form_for @comment, url: place_comments_path(@place), remote: true do |f| %>
  <div class="modal-body">
   <%= f.collection_radio_buttons :rating, [[1, image_tag('star-empty.png')] ,[2, image_tag('star-empty.png')], [3, image_tag('star-empty.png')], [4, image_tag('star-empty.png')], [5, image_tag('star-empty.png')]], :first, :last %>
    <%= f.input :message, label: "Your comment" %>
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal">Close</button>
  <%= f.submit "Add a Comment", class: 'btn btn-primary', id: 'comment-create-button' %>
<% end %>

app/views/comments/_form_create.html.erb
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="commentModalLabel">Add a comment</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <%= f.collection_radio_buttons :rating, [[1, image_tag('star-empty.png')] ,[2, image_tag('star-empty.png')], [3, image_tag('star-empty.png')], [4, image_tag('star-empty.png')], [5, image_tag('star-empty.png')]], :first, :last %>
          <%= f.input :message, label: "Your comment" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form_update.html.erb
<div class="modal fade" id="commentUpdate<%= comment.id %>Modal" tabindex="-1" role="dialog" aria-labelledby="commentUpdate<%= comment.id %>Modal" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title" id="commentUpdate<%= comment.id %>Modal">Add a comment</h4>
                </div>
                <div class="modal-body">
                    <%= simple_form_for comment, url: place_comment_path(@place, comment) do |f| %>
                    <%= f.collection_radio_buttons :rating, [[1, image_tag('star-empty.png')] ,[2, image_tag('star-empty.png')], [3, image_tag('star-empty.png')], [4, image_tag('star-empty.png')], [5, image_tag('star-empty.png')]], :first, :last %>
                    <%= f.input :message, label: "Your comment" %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <%= f.submit "Edit Comment", class: 'btn btn-primary' %>
                </div>
                <% end %>  
            </div>
          </div>
        </div>
        <div class="clear"></div>      
        <button class="btn btn-primary pull-left" data-toggle="modal" data-target="#commentUpdate<%= comment.id %>Modal">
          Edit Comment
        </button> 

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  $('#comment-display').append('<%= j render @comment %>');
  $('#commentModal').modal('hide');
<% else %>
  $("#commentForm").html("<%= j render(partial: 'comments/form') %>");
<% end %>

app/views/comments/temp.html.erb
      <blockquote>
    <b><%= comment.rating %></b> -
      <%= comment.message %>
    <small><%= link_to comment.user.username, user_path(comment.user) %></small>
  </blockquote> 

  <% if current_user %>
    <% if current_user == comment.user || current_user.admin? %>
      <!-- Modal -->
      <div class="modal fade" id="commentUpdate<%= comment.id %>Modal" tabindex="-1" role="dialog" aria-labelledby="commentUpdate<%= comment.id %>Modal" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="commentUpdate<%= comment.id %>Modal">Add a comment</h4>
            </div>
            <div class="modal-body">
                <%= simple_form_for comment, url: place_comment_path(@place, comment) do |f| %>
                <%= f.collection_radio_buttons :rating, [[1, image_tag('star-empty.png')] ,[2, image_tag('star-empty.png')], [3, image_tag('star-empty.png')], [4, image_tag('star-empty.png')], [5, image_tag('star-empty.png')]], :first, :last %>
                <%= f.input :message, label: "Your comment" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Edit Comment", class: 'btn btn-primary' %>
            </div>
            <% end %>  
        </div>
      </div>
    </div>
    <div class="clear"></div>      
    <button class="btn btn-primary pull-left" data-toggle="modal" data-target="#commentUpdate<%= comment.id %>Modal">
      Edit Comment
    </button> 
    <br />
    <% end %>
  <% end %>

app/views/comments/update.js.erb
alert("update");
<% if @comment.persisted? %>
  alert("update");
  $('#comment-display').append('<%= j render @comment %>');
  $('#commentUpdateModal').modal('hide');
<% else %>
  $("#commentForm").html("<%= j render(partial: 'comments/form') %>");
<% end %>