config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root 'statics#index'
  
  resources :places do
    resources :comments, only: [:create, :update]
    resources :photos, only: :create
    collection do
      get :search, to: "places#search"
    end
  end
  
  resources :users, only: [:show, :update]
  resource :dashboard, only: [:show]
  
  namespace :admin do
    resources :places, only: [:destroy]
  end
  
  resources :buckets, only: [:update, :destroy]  
  resources :completed_buckets, only: [:index, :destroy]
  
  get "/places/:place_id/photos", to: "galleries#index", as: "galleries"
  
  resources :photos, only: [:show, :destroy]
  
  
  get 'bucketlist', to: 'buckets#index'
  post 'bucketlist', to: 'buckets#create'
  
end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :place
  
  scope :todo, -> { where(list_state: "todo") }
  scope :done, -> { where(list_state: "done") }
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @buckets = current_user.buckets.todo
  end
  
  def create
    @place = Place.find(params[:place_id])
    Bucket.create(place: @place, user: current_user, position: last_position, list_state: "todo") unless current_user.buckets.map(&:place).include?(@place)
    redirect_to bucketlist_path
  end
  
  def update
    @bucket = Bucket.find(params[:id])
    @bucket.update_attributes(bucket_params)
    if @bucket.valid?
      redirect_to bucketlist_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @bucket = Bucket.find(params[:id])
    @bucket.destroy
    redirect_to bucketlist_path
  end
  
  private
  
  def last_position
    current_user.buckets.count + 1
  end
  
  def bucket_params
    params.require(:bucket).permit(:position, :list_state)
  end
end

app/views/buckets/index.html.erb
<div class="container main">
  <%= render 'shared/messages' %>
  <div class="col-xs-10 col-xs-offset-1">
    <h2>My Bucket List</h3>   
    <h4><%= link_to 'Go To Items Completed', completed_buckets_path, class: 'pull-right' %></h4>
    <br />
    <% if @buckets.empty? %>
      <h4> Nothing on list yet.</h4>
    <% else %>
      <% @buckets.each do |bucket| %>
        <div class="booyah-box col-xs-10 col-xs-offset-1">
          <h3><%= link_to bucket.place.name, place_path(bucket.place) %></h3>
          <br />
          <p><%= bucket.place.address %></p>
          <br />
          <div class="pull-left">
            <%= link_to image_tag('check.png', width: '50'), bucket_path(bucket, bucket: {id: bucket.id, place_id: bucket.place.id, user_id: current_user.id, list_state: "done"}), method: :put %>  
              <br />
              <p>I did it!</p>  
          </div>  
          <div class="pull-right">
            <%= link_to image_tag('bucket_delete.png', width: '50'), bucket_path(bucket, bucket: {id: bucket.id, place_id: bucket.place.id, user_id: current_user.id}), method: :delete %>
            <br />
            <p>Remove</p>  
          </div>  
        </div>    
      <% end %>
    <% end %>
  </div>
</div>  


 


 