config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root 'statics#index'
  
  resources :places do
    resources :comments, only: [:create, :update]
    resources :photos, only: :create
    collection do
      get :search, to: "places#search"
    end
  end
  
  resources :users, only: [:show, :update]
  resource :dashboard, only: [:show]
  
  namespace :admin do
    resources :places, only: [:destroy]
  end
  
  resources :buckets, only: [:update, :destroy]  
  resources :completed_buckets, only: [:index, :destroy]
  
  get "/places/:place_id/photos", to: "galleries#index", as: "galleries"
  
  resources :photos, only: [:show, :destroy]
  
  
  get 'bucketlist', to: 'buckets#index'
  post 'bucketlist', to: 'buckets#create'
  
end

app/models/place.rb
class Place < ActiveRecord::Base
  include PgSearch
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :buckets, dependent: :destroy
  has_many :place_categories
  has_many :categories, through: :place_categories
  
  geocoded_by :address
  after_validation :geocode
  
  validates :name, presence: true, length: { minimum: 3 }
  validates :address, presence: true
  
  def geocode
    if latitude.blank? && longitude.blank?
      super
    end
  end
  
  def avg_rating
    comments.average(:rating) if comments.average(:rating)
  end
  
   pg_search_scope :kinda_spelled_like,
                  :against => [:name, :address],
                  :using => { :tsearch => { :prefix => true },
                  :trigram => { :only => :name }
                    }

end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < AdminsController
  before_filter :authenticate_user!
  before_filter :require_admin
  
  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update]
  
  def index
    @places = Place.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.json{render json: @places}
      format.xml{render xml: @places}
    end
  end
  
  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :search, status: :unprocessable_entity
    end
  end
  
  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end
  
  def edit
    @place = Place.find(params[:id])
    
    return render text: 'Not Allowed', status: :forbidden unless @place.user == current_user || current_user.admin?
  end
  
  def update
    @place = Place.find(params[:id])
    return render text: 'Not Allowed', status: :forbidden unless @place.user == current_user || current_user.admin?
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def search
    @results = Place.kinda_spelled_like(params[:q])
    @place = Place.new
  end
  
  private
  
  def place_params
    if current_user.admin? || @place.nil?
      params.require(:place).permit(:name, :address, :description)
    else
      params.require(:place).permit(:description)
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form_create.html.erb
  <div class="modal fade" id="placeModal" tabindex="-1" role="dialog" aria-labelledby="placeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="placeModalLabel">Add a place</h4>
        </div>
        <div class="modal-body">
           <%= simple_form_for @place do |f| %>
            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :description %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Create', class: 'button-normal' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/places/_map.html.erb
 <style>
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    #map {
      height: 300px;
    }
  </style>

  <div class="col-xs-8">  
    <% if !(@place.latitude.present? && @place.longitude.present?) %>

    <script>
      function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv, {
            center: {lat: 35.6892, lng: 51.3890},
            zoom: 2
        });
      }
    </script>

    <div id="map"></div>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC__9rFHF6oY5IK7HsZ6mz4tVbeUKIbiis&callback=initMap">
    </script>



    <% else %>
    <script>

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

    <div id="map"></div>

    <% end %>
  </div>  

<script async defer
   src="https://maps.googleapis.com/maps/api/js?key=
    AIzaSyC__9rFHF6oY5IK7HsZ6mz4tVbeUKIbiis&callback=initMap">
</script>

app/views/places/edit.html.erb
<div class="container main">
  <%= render 'shared/messages' %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1>Enter Your Place Details</h1>
    <br />
    <%= simple_form_for @place do |f| %>
      <% if current_user.admin == true %>
        <%= f.input :name %>
        <br />
        <%= f.input :address %>
        <br />
      <% else %>
        <h3>Name: <%= @place.name %></h3>
        <br />
        <h3>Address: <%= @place.address %></h3>
        <br />
      <% end %>
      <%= f.input :description %>
      <br />
      <%= f.submit 'Update', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/places/index.html.erb
<div class="container main">
  <%= render 'shared/messages' %>   
  <% @places.each do |place| %>
    <div class="booyah-box col-md-10 col-md-offset-1">
      <div class="col-md-3 thumbnail-index">
       <% if place.photos.any? %>
        <%= image_tag(place.photos.first.image_url, :width=>'200', :height=>'200', :crop=>"fill") %>
      <% else %>  
        <%= image_tag('nasa.jpg', :width=>'200', :height=>'200') %>
      <% end %>  
      </div>  
      <div class="col-md-7" style="margin-left:30px;">
      <h2><%= link_to place.name, place_path(place) %></h2>
      <p><%= place.address %></p>
      <p><%= place.description %></p>
      <p>
        <% if place.avg_rating %>
          <% place.avg_rating.to_i.times do %>
            <%= image_tag('star-full.png') %>
          <% end %>
          <% if place.avg_rating % 1 > 0.2 && place.avg_rating % 1 < 0.8 %>
            <%= image_tag('star-half.png') %>
          <% end %>
        <% end %>   
      </p>  
      <br />  
      <% if place.categories.any? %>
        <p>
          <% place.categories.each do |category| %>
            <span class="category"><%= category.name %></span>
          <% end %>
        </p>  
      <% end %>  
      <% if current_user && current_user.admin %>
        <p class="warn"><%= link_to "Delete Place", admin_place_path(place), method: :delete, data: { confirm: "Are you certain you want to delete #{place.name}" } %></p>
      <% end %>  
      </div>  
    </div>
    
    <hr />
  <% end %>

  <%= will_paginate @places, previous_label: h("<"), next_label: h(">") %>
</div> 

app/views/places/search.html.erb
<div class="container main">
  <h3>Search Results</h3>
  <br />
  <h4>Didn't find what you were looking for?</h4> 
  <br />
  
  <% if user_signed_in? %>
     <!-- Place Create Modal -->
     <%= render partial: "places/form_create" %>

    <!-- Place create button trigger modal -->
    <button class="btn button-opposite pull-left" data-toggle="modal" data-target="#placeModal">
      Add a place
    </button>
  
  <div class="clear"></div>
  <% else %>
    <h4><%= link_to 'Sign in', new_user_session_path %> to add a place</h4>
    <br />
  <% end %>
  
  <% if false %>    
    <% if !(user_signed_in?) %>
      <!-- Sign in Modal -->
      <%= render partial: "devise/sessions/sign_in" %>
       <!-- Sign in button trigger modal -->
      <button class="btn button-opposite pull-left" data-toggle="modal" data-target="#sessionModal">
        Sign In
      </button>
      <div class="clear"></div>
    <% end %>
  <% end %>
  

  <br />
  <br />
  <br />
  <% @results.each do |result| %>
    <h4><%= link_to result.name, place_path(result) %></h4>
    <p><%= result.address %></p>
    <br />
    <% if current_user && current_user.admin %>
      <p class="warn"><%= link_to "Delete Place", admin_place_path(result), method: :delete, data: { confirm: "Are you certain you want to delete #{result.name}" } %></p>
    <% end %>  
  <% end %>
</div>

app/views/places/show.html.erb
<div class="container main">
  <%= render 'shared/messages' %>
  <div class="row booyah-box">

    <div class="col-md-4">  
      <h1><%= @place.name %></h1>
      <br />  
      <i><%= @place.address %></i>
      <br/>
      <br/>
      <h3>
      <% if @place.avg_rating %>
        <% @place.avg_rating.to_i.times do %>
          <%= image_tag('star-full.png') %>
        <% end %>
        <% if @place.avg_rating % 1 > 0.2 && @place.avg_rating % 1 < 0.8 %>
          <%= image_tag('star-half.png') %>
        <% end %>
      <% end %>
      </h3>
      <br />
      <p><%= @place.description %></p>

      <div class="pull-left">
        <% if current_user %> 
          <% if current_user == @place.user || current_user.admin? %>  
            <%= link_to 'Edit Description', edit_place_path(@place) %>
          <% end %>
        <% end %>
      </div>  
    </div>  
    
     <!-- Button trigger modal --> 
    <div class="btn-group">
      <button class="btn pull-right button-opposite" data-toggle="modal" data-target="#photoModal">
        Add a photo
      </button>
      <% if current_user %>
        <button class="btn pull-right button-opposite" data-toggle="modal" data-target="#commentModal">
          Add a comment
        </button>
      <% else %>
        <%= link_to 'Add a comment', new_user_session_path(redirect_to: place_path(@place,{comment_modal: true})), class: "btn pull-right button-opposite" %>
      <% end %>
    </div>
    <div class="pull-right">
      <% if current_user %>
        <% if !(current_user.buckets.map(&:place).include?(@place)) %>
          <%= link_to '+ Bucket List', bucketlist_path(place_id: @place), method: :post, class: 'btn button-opposite' %>
        <% end %>
      <% else %>
        <h4><%= link_to 'Sign in', new_user_session_path %></h4>
      <% end %>
    </div>  
    <br />  
    <br /> 
    <br />     
    <%= render partial: "places/map" %>
    <br /> 
    <br /> 
  </div>  

  <% if @place.photos.any? %>
    <div class="row place-photos">
      <% @place.photos.last_three_photos(@place).each do |photo| %>
        <div class="col-md-4"> 
          <div id="mycarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="item active">
                <%= link_to image_tag(photo.image_url, :width=>320, :height=>300, :crop=>"fill"), photo_path(photo) if photo.image? %>
              <div class="carousel-caption">
                <%= photo.caption if photo.caption? %>
              </div>
            </div>
          </div>
         </div>
        </div>  
       <% end %>
      </div>
    <br />
  <h4><%= link_to 'See All Photos', galleries_path(place_id: @place.id) %></h4>
  <% end %>
  
  <div class="clear"></div>

  <% if current_user %>
    <!-- Photo Create Modal -->
     <%= render partial: "photos/form_create" %>
  <% end %>

  <% if current_user %>
    <!-- Comment Create Modal -->
    <%= render partial: "comments/form_create" %>
  <% end %>

  <div class="clear"></div>

  <br />
  <br />
  <br />

  <h3>Comments</h3>
  <% if @place.comments.empty? %>
    <br />
    <p>Be the first to comment.</p>
  <% end %>
  <% @place.comments.each do |comment| %>
    <blockquote>
      <h4>
      <% if comment.rating %>
        <% comment.rating.to_i.times do %>
          <%= image_tag('star-full.png') %>
        <% end %>
      <% end %>
      </h4>  
      <br />
      <p><%= comment.message %></p>
      <br />
      <small><%= link_to comment.user.username, user_path(comment.user) %></small>
    </blockquote> 
    <% if current_user %>
      <% if current_user == comment.user || current_user.admin? %>
        <!-- Comment Update Modal -->
        <%= render partial: "comments/form_update", locals: {comment: comment} %>         
        <br />
      <% end %>
    <% end %>
  <% end %>
</div>  

<script>
  $(function(){
    <% if params[:comment_modal] %>
      $('#commentModal').modal('show');
    <% end %>
  });
</script>  