config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root 'statics#index'
  
  resources :places do
    resources :comments, only: [:create, :update]
    resources :photos, only: :create
    collection do
      get :search, to: "places#search"
    end
  end
  
  resources :users, only: [:show, :update]
  resource :dashboard, only: [:show]
  
  namespace :admin do
    resources :places, only: [:destroy]
  end
  
  resources :buckets, only: [:update, :destroy]  
  resources :completed_buckets, only: [:index, :destroy]
  
  get "/places/:place_id/photos", to: "galleries#index", as: "galleries"
  
  resources :photos, only: [:show, :destroy]
  
  
  get 'bucketlist', to: 'buckets#index'
  post 'bucketlist', to: 'buckets#create'
  
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'Dream Places', root_path, class: 'navbar-brand', id: 'navbar-brand' %>
    </div>
    <div class="form-group navbar-form" role="search">
       <%= form_tag search_places_path, :method => 'get' do %>
       <%= text_field_tag :q, nil, :class => 'search-box', :placeholder => 'Search Places' %>
       <%= submit_tag "Search", :class => 'btn button-normal' %>
       <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right menu-items" id="menu-items">
        <li><%= link_to 'Browse', places_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'My Bucket List', bucketlist_path %></li>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dream</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class="container-fluid">
  <header>
    <%= render 'layouts/navigation' %>
  </header>
</div>  
<body>

<%= yield %>

</body> 
</html>